language: c
sudo: required
services:
  - docker
env:
  global:
    - REPO=bcal

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
#    - os: linux
#      compiler: musl-gcc
#      addons:
#        apt:
#          packages: &musl_packages
#          - musl
#          - musl-dev
#          - musl-tools
    - os: osx
      compiler: gcc
    - os: osx
      compiler: clang

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
        sudo apt-get update -qy;
        sudo apt-get install -qy python3 python3-pip;
        python -m pip install logilab-common --user;
        python -m pip install pytest --user;
    fi
  - if [ $TRAVIS_OS_NAME = osx ]; then
        brew upgrade python;
        pip3 install logilab-common;
        pip3 install pytest;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then if [[ "$CC" == "clang" ]]; then brew update; brew install llvm; export PATH="/usr/local/opt/llvm/bin:$PATH"; fi; fi

script:
  - make clean; make strip;
  - pytest -p no:cacheprovider ./test.py;
  - make clean;
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then if [[ "$CC" == "clang" ]]; then clang-tidy **/*.h **/*.c -- -Iinc; fi; fi

before_deploy:
  - cd ..
  - rm -rf $REPO/.git
  - tar -czf $REPO-${TRAVIS_TAG}.tar.gz $REPO
  - cd $REPO
  - sudo apt-get update -qy
  - sudo apt-get install -qy python3 python3-pip
  - sudo python3 -m pip install --upgrade pip
  - sudo python3 -m pip install --upgrade packagecore setuptools
  - packagecore -o dist/ "${TRAVIS_TAG#v}"
  - mv ../$REPO-${TRAVIS_TAG}.tar.gz dist/

deploy:
  provider: releases
  api-key:
    secure: ZtMbo/H21MoodNvw7+tvPId97meS4Xs2beUzqOhI166iuaLSWtjXxQgeC7vdYTWgPNacN6gxwhnXTLMXpt81a7g0NWxjRQ72/Rwh7aCdgQkJI/Y+0c7RNNVdLOtAWBM8csPoJy0jFdI34yHRj053tm9x65V4fMEKC9ArRm7pbTjNNovYXbW2KmRh6kr3dJdB/7tpoCpiMov6l4uHyWIcniFx97P+3dGnGqBd8SpR3IxeEypm8fzIGiX7NIJqwyG5MbLaWoyloBu21ilwh07dDifF6MI4mrkxtGY0yQ9GtHVp5cr7qyMgCt60hUGtrKhTtPQWwpzK0GSZ5eeYiLt6I/kkcj8FkWP+OazRLy/MydjGtG7q8tnbgNcmGqsbv+g1jJMEfZsnTfozeGOPPsYlhB/7kCi2BVqguXlKMRmpNPMZsc4HYK9yjV4HNsEkmwJcXgD350XS5iFu/koIGiT2PJ+/msdwPir74JpgRn00iGC0fD25V8M2TRnKn43g6jNRAZYMITaYDx+ML0SkdWIjksalW0759BgLfQopNbs9a9PbsKiNbfRRRF3xA8j2fQI6my7hXx0TzRwWTC7aMAuJkdjKn5UYOrMAZ+VXhHSOcX5LPiefwgtoU0YGjgWQdgTkQ7aR13rKuDSKepGonnkyiHWnM9gGftnNbNFi7WZRk5w=
  file_glob: true
  file:
    - dist/*
  skip_cleanup: true
  on:
    condition:
      - "$TRAVIS_OS_NAME == linux"
      - "$CC == gcc"
    tags: true
    repo: jarun/bcal
